# Generated by Django 2.0.7 on 2019-03-17 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='article',
            name='on_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='on_topic', to='common.Topic', verbose_name='所属话题'),
        ),
        migrations.AlterField(
            model_name='article',
            name='special_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='special_column', to='common.SpecialColumn', verbose_name='所属专栏'),
        ),
    ]
